# Generated by Django 2.2.13 on 2020-06-19 15:32

from django.db import migrations, models
import django.db.models.deletion
import faces.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=faces.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instate', models.BooleanField(default=True)),
                ('precision', models.FloatField(blank=True)),
                ('unknown_number', models.SmallIntegerField(blank=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='persons.Person')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaceDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=faces.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_type', models.CharField(choices=[('Train', 'train'), ('Test', 'test')], default='train', max_length=10)),
                ('model', models.CharField(blank=True, default='', max_length=35)),
                ('label', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces_dataset', to='persons.Person')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
