# Generated by Django 2.2.12 on 2020-05-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaceDataSet',
        ),
    ]
