# Generated by Django 2.2.12 on 2020-05-23 15:57

from django.db import migrations, models
import django.db.models.deletion
import faces.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_remove_label_avatar'),
        ('faces', '0002_delete_facedataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=faces.models.upload_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_type', models.CharField(choices=[('Train', 'train'), ('Test', 'test')], default='train', max_length=10)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces_dataset', to='persons.Person')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
