# Generated by Django 2.2.12 on 2020-05-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_facedataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='facedataset',
            name='unknown_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='facedataset',
            name='label',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces_dataset', to='persons.Person'),
        ),
    ]
