# Generated by Django 2.2.13 on 2020-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_pointage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='date_entree',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='date_sortie',
            field=models.DateTimeField(null=True),
        ),
    ]
