# Generated by Django 2.2.12 on 2020-05-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_auto_20200526_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facedataset',
            name='unknown_number',
        ),
        migrations.AddField(
            model_name='facedetected',
            name='unknown_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
