# Generated by Django 2.2.13 on 2020-06-08 15:58

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True)),
                ('avatar', models.ImageField(blank=True, upload_to=persons.models.upload_image_path)),
                ('matricule', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('labels', models.ManyToManyField(blank=True, related_name='persons', to='persons.Label')),
            ],
        ),
    ]
