# Generated by Django 2.2.13 on 2020-06-09 10:18

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=persons.models.upload_image_path),
        ),
    ]
