# Generated by Django 2.2.13 on 2020-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200819_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
