# Generated by Django 2.2.12 on 2020-04-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_auto_20200414_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='labels',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
