# Generated by Django 2.2.12 on 2020-04-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_person_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='labels',
        ),
        migrations.AddField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(blank=True, to='persons.Label'),
        ),
    ]
