# Generated by Django 2.2.15 on 2020-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_auto_20200819_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
