# Generated by Django 2.2.12 on 2020-04-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_auto_20200420_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(to='persons.Label'),
        ),
    ]
