# Generated by Django 2.2.12 on 2020-04-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20200420_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(blank=True, to='persons.Label'),
        ),
    ]
