# Generated by Django 2.2.12 on 2020-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0007_auto_20200420_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='persons',
        ),
        migrations.AddField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='persons.Label'),
        ),
    ]
