# Generated by Django 2.2.12 on 2020-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0008_auto_20200420_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(related_name='persons', to='persons.Label'),
        ),
    ]
