# Generated by Django 2.2.12 on 2020-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0009_auto_20200420_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
