# Generated by Django 2.2.12 on 2020-04-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0010_auto_20200420_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(related_name='labels', to='persons.Label'),
        ),
    ]
