# Generated by Django 2.2.12 on 2020-04-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0011_auto_20200420_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(related_name='persons', to='persons.Label'),
        ),
    ]
