# Generated by Django 2.2.12 on 2020-04-21 14:30

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0012_auto_20200420_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=persons.models.upload_image_path),
        ),
    ]
