# Generated by Django 2.2.12 on 2020-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0013_person_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='persons', to='persons.Label'),
        ),
    ]
