# Generated by Django 2.2.12 on 2020-04-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0014_auto_20200421_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons', to='persons.Label'),
        ),
    ]
