# Generated by Django 2.2.12 on 2020-04-21 21:07

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0015_auto_20200421_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=persons.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name='person',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='persons', to='persons.Label'),
        ),
    ]
