# Generated by Django 2.2.12 on 2020-04-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0016_auto_20200421_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='avatar',
        ),
    ]
