# Generated by Django 2.2.12 on 2020-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0017_remove_label_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='matricule',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(blank=True),
        ),
    ]
