# Generated by Django 2.2.12 on 2020-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0018_auto_20200526_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
